version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/To-Do/To-Do-List-Back/public
permissions:
  - object: /home/ubuntu/To-Do-List-Back/public
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file
