version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/To-Do/WebPage
permissions:
  - object: /home/ubuntu/To-Do/WebPage
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file
