version: 0.0
os: linux
files:
  - source: ./
    destination: /home/ubuntu/To-Do/To-Do-List-Front
permissions:
  - object: /home/ubuntu
    owner: ubuntu
    group: ubuntu
    mode: 755
    type:
      - directory
      - file
hooks:
  ApplicationStart:
    - location: script/build.sh
      timeout: 300
      runas: ubuntu
